# -*- coding: utf-8 -*-
"""functions in python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vr9ptr_Sq321ySPutvWosh2DRZuE6M_n

## Mini Challenge

Write a function that checks whether a given string is a palindrome.
"""

def is_palindrome(s):
    s = s.lower().replace(" ", "")
    return s == s[::-1]

word = "Madam"
print(f"Is '{word}' a palindrome?", is_palindrome(word))

"""**Calculator**"""

def add(*args):
  return sum(args)

def sub(*args):
  result = args[0]
  for num in args[1:]:
    result -= num
  return result

def mul(*args):
  result = args[0]
  for num in args[1:]:
    result*=num
  return result

def div(*args):
  result = args[0]
  for num in args[0]:
    result/+num
  return result


number=[]
operation=input("Enter the operator + , - , * , / \n")
lim=int(input("Enter the limit\t"))
for i in range(1,lim+1):
  values=int(input("Enter the values\t"))
  number.append(values)

match operation:
  case "+":print(f"Sum of {lim} numbers = {add(*number)} ")
  case "-":print(f"Difference of {lim} numbers = {sub(*number)} ")
  case "*":print(f"Product of {lim} numbers = {mul(*number)} ")
  case "/":print(f"Quotient of {lim} numbers = {div(*number)} ")
  case _ :print("Invalid operator \n")

def add(a,b):
  return a+b

def sub(a,b):
  return a-b

def mul(a,b):
  return a*b

def div(a,b):
  return a/b

print("CALCULATOR PROGRAM")
print("-----------------------------------------------------")
n1= int(input("Enter the first number\t"))
op= input("Enter the operator \n + for addition \n - for subtraction \n * for multiplication \n / for division\n\n ")
if op=="+" or op=="-" or op=="*" or op=="/":
  n2= int(input("Enter the second number \t"))
else:
  print("Invalid operator")

match op:
  case "+":print(f"{n1} + {n2} = {add(n1,n2)}")
  case "-":print(f"{n1} - {n2} = {sub(n1,n2)}")
  case "*":print(f"{n1} x {n2} = {mul(n1,n2)}")
  case "/":print(f"{n1} / {n2} = {div(n1,n2)}")
  case _:print("Invalid operator used")

def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def mul(a, b):
    return a * b

def div(a, b):
    return a / b if b != 0 else "Error: Division by zero"

num = []
oper = []

while True:
    n = int(input("Enter the number: "))
    num.append(n)

    o = input("Enter the operator: ")
    oper.append(o)

    if o == "=":
        break


result = num[0]
for i in range(len(oper) - 1):
    if oper[i] == "+":
        result = add(result, num[i + 1])
    elif oper[i] == "-":
        result = sub(result, num[i + 1])
    elif oper[i] == "*":
        result = mul(result, num[i + 1])
    elif oper[i] == "/":
        result = div(result, num[i + 1])

print("Result:", result)

