# -*- coding: utf-8 -*-
"""python loops mini challenges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Su7GCNufDvQSBmCAFun4HmMrOhLpwIt2

# Mini Challenges
## for loop

1. **Print numbers 1 to 10**
   Write a `for` loop to print all numbers from **1 to 10**.
"""

for i in range(1,11):
  print(i,end=" ")

"""2. **Print even numbers**
   Use a `for` loop to print only **even numbers between 1 and 20**.
"""

for i in range(2,22,2):
  print(i,end=" ")

"""3. **Sum of first N natural numbers**
   Write a program that asks the user for a number `N` and prints the **sum of numbers from 1 to N** using a `for` loop.
"""

n=int(input("ENTER THE VALUE,\t"))
s=0
for i in range(1,n+1):
  s=i+s

print(f"{s} , IS SUM OF THE {n} VALUES")

"""4. **Squares of numbers**
   Use a `for` loop to print the **square of numbers from 1 to 10**.

"""

for i in range(1,11):
  print(i*i,end=" ")

"""5. **Characters in a string**
   Write a program to print each character of the string `"PYTHON"` using a `for` loop.

"""

for i in "python":
  print(i,end=" ")

"""6. **List elements**
   Given a list:

```python
marks = [45, 67, 89, 32, 76]
```

Write a program to print all marks greater than **50** using a `for` loop.
"""

marks = []
for i in range(5):
 lis=int(input("enter the marks"))
 marks.append(lis)
for i in marks:
  if i>=90:
    print(i," a grade")
  elif i>80:
    print(i," b  grade")
  elif i>70:
    print(i," c grade" )
  elif i>60:
    print(i," d grade")

"""7. **Reverse order printing**
   Use a `for` loop with `range()` to print numbers from **10 down to 1**.
"""

for i in range(11,0,-2):
  print(i)

"""8. **Multiplication table of a number**
   Ask the user for a number and print its **multiplication table up to 10** using a `for` loop.

"""

b=int(input("enter the number"))
for i in range(1,10):
  print(f"{i}x{b}={i*b}")

"""9. **Factorial using for loop**
   Write a program to calculate the **factorial of a given number** using a `for` loop.

"""

n=int(input("enter the no\t"))
fact=1
for i in range(n,1,-1):
  fact=i*fact
print(f"factorial of\t{n}={fact}")

"""10. **Nested for loop – Pattern printing**
    Write a program to print the following pattern using nested `for` loops:

```
*
* *
* * *
* * * *
* * * * *
```

"""

for i in range(5):
  print()

  for j in range(i):
     print("*",end=" ")

"""## While Loop in Python

1. **Print numbers 1 to 10**
   Write a `while` loop to print all numbers from **1 to 10**.
"""

number=1
while number <=10:
  print(number,end=" ")
  number +=1

"""2. **Countdown timer**
   Use a `while` loop to print numbers from **10 down to 1**.

"""

count=10
while count >=1:
  print(count,end=" ")
  count -=1

"""3. **Sum of first N natural numbers**
   Write a program that asks the user for a number `N` and calculates the **sum of numbers from 1 to N** using a `while` loop.
"""

no=int(input("enter rhe numbers\t"))
i=1
sum=0
while i<=no:
  sum=sum+i
  i+=1
print(sum)

"""4. **Print even numbers**
   Use a `while` loop to print only **even numbers between 1 and 20**.
"""

even=2
while even <=20:
  print(even)
  even +=2

"""5. **Password check**
   Write a program that keeps asking the user to enter the correct password (`"python123"`) until they get it right.

"""

pasw="python123"
attempt=0
pwd=input("enter tour password\t")
while pasw!=pwd:
  pwd=input("try again\t")
  if attempt==3:
    print("over\t")
    break
  attempt+=1
else:
  print("loging successfull")

"""6. **Reverse a number**
   Use a `while` loop to reverse the digits of a given number.
   *(Example: Input → 1234, Output → 4321)*

"""

n=1234
while n!=0:
  r=n%10
  n=n//10
  print(r,end="")

"""7. **Digits count**
   Write a program that counts how many digits are in a number using a `while` loop.

"""

n=int(input("enter the number\t"))
count=0
while n!=0:
  n=n//10
  count+=1
print(count)

"""8. **Factorial using while loop**
   Write a program to calculate the **factorial of a number** using a `while` loop.

"""

n=int(input("enter the value "))
fact=1
i=1
while i<=n:
  fact=fact*i
  i+=1
print(f"factorial of\t{n}={fact}")

"""9. **Sum of digits**
   Use a `while` loop to calculate the sum of digits of a given number.
   *(Example: 123 → 1+2+3 = 6)*
"""

n=int(input("enter the number"))
sum=0
while n!=0:
  r=n%10
  n=n//10
  sum=r+sum
print(sum)

"""10. **Guess the number game**
    Write a program where the computer has a secret number (say 7).
    Keep asking the user to guess until they get it right, and print how many attempts it took.

"""

no=10
attempt=0
paw=int(input(" gess the no"))
while paw!=no:
  paw=int(input("try again"))
  attempt+=1
print(f"you found it in {attempt} attempt")

